# Generated by Django 4.2.11 on 2025-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('total_marks', models.IntegerField()),
            ],
            options={
                'db_table': 'my_exam_table',
            },
        ),
    ]
